# Generated by Django 3.0.5 on 2020-09-08 13:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('umm', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='age',
            new_name='posted',
        ),
        migrations.RenameField(
            model_name='post',
            old_name='no',
            new_name='status',
        ),
    ]
