# Generated by Django 3.2.7 on 2021-11-12 19:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('umm', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mechanics',
            name='identity',
            field=models.CharField(default='korola', max_length=100),
        ),
    ]
