# Generated by Django 3.0.5 on 2020-09-08 13:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('umm', '0002_auto_20200908_1930'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='posted',
            new_name='age',
        ),
        migrations.RenameField(
            model_name='post',
            old_name='status',
            new_name='no',
        ),
    ]
