# Generated by Django 3.0.5 on 2020-09-08 14:13

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('umm', '0003_auto_20200908_1932'),
    ]

    operations = [
        migrations.CreateModel(
            name='Phone',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=100)),
                ('Description', models.TextField()),
                ('Posted', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
    ]
