# Generated by Django 3.0.5 on 2020-09-08 17:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('umm', '0006_auto_20200908_2225'),
    ]

    operations = [
        migrations.AddField(
            model_name='phone',
            name='Brand',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='phone',
            name='Price',
            field=models.FloatField(default=1),
            preserve_default=False,
        ),
    ]
