# Generated by Django 3.0.5 on 2020-09-09 09:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('umm', '0007_auto_20200908_2315'),
    ]

    operations = [
        migrations.RenameField(
            model_name='phone',
            old_name='Name',
            new_name='Model',
        ),
        migrations.AddField(
            model_name='phone',
            name='Size',
            field=models.FloatField(default=1),
            preserve_default=False,
        ),
    ]
