# Generated by Django 3.2.6 on 2021-10-01 18:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('umm', '0010_rename_no_post_content'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='content',
            new_name='no',
        ),
    ]
