# Generated by Django 3.2.6 on 2021-10-01 20:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('umm', '0011_rename_content_post_no'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='review',
            name='on',
        ),
        migrations.RemoveField(
            model_name='review',
            name='pt',
        ),
        migrations.RenameField(
            model_name='post',
            old_name='no',
            new_name='content',
        ),
        migrations.DeleteModel(
            name='Phone',
        ),
        migrations.DeleteModel(
            name='Review',
        ),
    ]
